changelog:
  exclude:
    labels:
      - 'invalid'
      - 'wontfix'
      - 'prototype'

  categories:
    - title: 🧱 Application
      labels: ['application']
    - title: 🧱 Database
      labels: ['database']
    - title: 🧱 Job
      labels: ['job']
    - title: 🧱 User management
      labels: ['user management']
    - title: 🧱 Evaluation
      labels: ['evaluation']

    - title: 🚀 General Improvements
      labels:
        - 'enhancement'
        - 'ui/ux improvement'

    - title: 🐛 Bug fixes
      labels:
        - 'bug'

    - title: 🔐 Security
      labels:
        - 'security fix'
        - 'Mend: dependency security vulnerability'
        - 'Mend: configuration error'

    - title: 📦 Dependencies
      labels:
        - 'dependencies'

    - title: 📝 Documentation
      labels:
        - 'documentation'

    - title: 🧪 Tests
      labels:
        - 'tests'

    - title: 🧰 Maintenance & Config
      labels:
        - 'task'
        - 'config-change'
        - 'shared'

    - title: 🏗 DevOps / Infra
      labels:
        - 'docker'
        - 'keycloak'

    - title: Other changes
      labels:
        - '*'
