import { SelectOption } from 'app/shared/components/atoms/select/select.component';

export const selectNationality: SelectOption[] = [
  { value: 'af', name: 'Afghan' },
  { value: 'al', name: 'Albanian' },
  { value: 'dz', name: 'Algerian' },
  { value: 'ad', name: 'Andorran' },
  { value: 'ao', name: 'Angolan' },
  { value: 'ag', name: 'Antiguan/Barbudan' },
  { value: 'ar', name: 'Argentine' },
  { value: 'am', name: 'Armenian' },
  { value: 'au', name: 'Australian' },
  { value: 'at', name: 'Austrian' },
  { value: 'az', name: 'Azerbaijani' },
  { value: 'bs', name: 'Bahamian' },
  { value: 'bh', name: 'Bahraini' },
  { value: 'bd', name: 'Bangladeshi' },
  { value: 'bb', name: 'Barbadian' },
  { value: 'by', name: 'Belarusian' },
  { value: 'be', name: 'Belgian' },
  { value: 'bz', name: 'Belizean' },
  { value: 'bj', name: 'Beninese' },
  { value: 'bt', name: 'Bhutanese' },
  { value: 'bo', name: 'Bolivian' },
  { value: 'ba', name: 'Bosnian/Herzegovinian' },
  { value: 'bw', name: 'Botswanan' },
  { value: 'br', name: 'Brazilian' },
  { value: 'bn', name: 'Bruneian' },
  { value: 'bg', name: 'Bulgarian' },
  { value: 'bf', name: 'Burkinabe' },
  { value: 'bi', name: 'Burundian' },
  { value: 'kh', name: 'Cambodian' },
  { value: 'cm', name: 'Cameroonian' },
  { value: 'ca', name: 'Canadian' },
  { value: 'cv', name: 'Cape Verdean' },
  { value: 'cf', name: 'Central African' },
  { value: 'td', name: 'Chadian' },
  { value: 'cl', name: 'Chilean' },
  { value: 'cn', name: 'Chinese' },
  { value: 'co', name: 'Colombian' },
  { value: 'km', name: 'Comoran' },
  { value: 'cg', name: 'Congolese' },
  { value: 'cd', name: 'Congolese (DRC)' },
  { value: 'cr', name: 'Costa Rican' },
  { value: 'ci', name: 'Ivorian' },
  { value: 'hr', name: 'Croatian' },
  { value: 'cu', name: 'Cuban' },
  { value: 'cy', name: 'Cypriot' },
  { value: 'cz', name: 'Czech' },
  { value: 'dk', name: 'Danish' },
  { value: 'dj', name: 'Djiboutian' },
  { value: 'dm', name: 'Dominican (DM)' },
  { value: 'do', name: 'Dominican (DO)' },
  { value: 'tl', name: 'Timorese' },
  { value: 'ec', name: 'Ecuadorian' },
  { value: 'eg', name: 'Egyptian' },
  { value: 'sv', name: 'Salvadoran' },
  { value: 'gq', name: 'Equatorial Guinean' },
  { value: 'er', name: 'Eritrean' },
  { value: 'ee', name: 'Estonian' },
  { value: 'et', name: 'Ethiopian' },
  { value: 'fj', name: 'Fijian' },
  { value: 'fi', name: 'Finnish' },
  { value: 'fr', name: 'French' },
  { value: 'ga', name: 'Gabonese' },
  { value: 'gm', name: 'Gambian' },
  { value: 'ge', name: 'Georgian' },
  { value: 'de', name: 'German' },
  { value: 'gh', name: 'Ghanaian' },
  { value: 'gr', name: 'Greek' },
  { value: 'gd', name: 'Grenadian' },
  { value: 'gt', name: 'Guatemalan' },
  { value: 'gn', name: 'Guinean' },
  { value: 'gw', name: 'Bissau-Guinean' },
  { value: 'gy', name: 'Guyanese' },
  { value: 'ht', name: 'Haitian' },
  { value: 'hn', name: 'Honduran' },
  { value: 'hu', name: 'Hungarian' },
  { value: 'is', name: 'Icelander' },
  { value: 'in', name: 'Indian' },
  { value: 'id', name: 'Indonesian' },
  { value: 'ir', name: 'Iranian' },
  { value: 'iq', name: 'Iraqi' },
  { value: 'ie', name: 'Irish' },
  { value: 'il', name: 'Israeli' },
  { value: 'it', name: 'Italian' },
  { value: 'jm', name: 'Jamaican' },
  { value: 'jp', name: 'Japanese' },
  { value: 'jo', name: 'Jordanian' },
  { value: 'kz', name: 'Kazakhstani' },
  { value: 'ke', name: 'Kenyan' },
  { value: 'ki', name: 'I-Kiribati' },
  { value: 'xk', name: 'Kosovar' },
  { value: 'kw', name: 'Kuwaiti' },
  { value: 'kg', name: 'Kyrgyz or Kyrgyzstani' },
  { value: 'la', name: 'Lao or Laotian' },
  { value: 'lv', name: 'Latvian' },
  { value: 'lb', name: 'Lebanese' },
  { value: 'ls', name: 'Mosotho (Basotho plural)' },
  { value: 'lr', name: 'Liberian' },
  { value: 'ly', name: 'Libyan' },
  { value: 'li', name: 'Liechtensteiner' },
  { value: 'lt', name: 'Lithuanian' },
  { value: 'lu', name: 'Luxembourger' },
  { value: 'mk', name: 'Macedonian' },
  { value: 'mg', name: 'Malagasy' },
  { value: 'mw', name: 'Malawian' },
  { value: 'my', name: 'Malaysian' },
  { value: 'mv', name: 'Maldivian' },
  { value: 'ml', name: 'Malian' },
  { value: 'mt', name: 'Maltese' },
  { value: 'mh', name: 'Marshallese' },
  { value: 'mr', name: 'Mauritanian' },
  { value: 'mu', name: 'Mauritian' },
  { value: 'mx', name: 'Mexican' },
  { value: 'fm', name: 'Micronesian' },
  { value: 'md', name: 'Moldovan' },
  { value: 'mc', name: 'Monégasque' },
  { value: 'mn', name: 'Mongolian' },
  { value: 'me', name: 'Montenegrin' },
  { value: 'ma', name: 'Moroccan' },
  { value: 'mz', name: 'Mozambican' },
  { value: 'mm', name: 'Burmese' },
  { value: 'na', name: 'Namibian' },
  { value: 'nr', name: 'Nauruan' },
  { value: 'np', name: 'Nepali' },
  { value: 'nl', name: 'Dutch' },
  { value: 'nz', name: 'New Zealander' },
  { value: 'ni', name: 'Nicaraguan' },
  { value: 'ne', name: 'Nigerien' },
  { value: 'ng', name: 'Nigerian' },
  { value: 'kp', name: 'North Korean' },
  { value: 'no', name: 'Norwegian' },
  { value: 'om', name: 'Omani' },
  { value: 'pk', name: 'Pakistani' },
  { value: 'pw', name: 'Palauan' },
  { value: 'ps', name: 'Palestinian' },
  { value: 'pa', name: 'Panamanian' },
  { value: 'pg', name: 'Papua New Guinean' },
  { value: 'py', name: 'Paraguayan' },
  { value: 'pe', name: 'Peruvian' },
  { value: 'ph', name: 'Filipino' },
  { value: 'pl', name: 'Polish' },
  { value: 'pt', name: 'Portuguese' },
  { value: 'qa', name: 'Qatari' },
  { value: 'ro', name: 'Romanian' },
  { value: 'ru', name: 'Russian' },
  { value: 'rw', name: 'Rwandan' },
  { value: 'kn', name: 'Kittitian and Nevisian' },
  { value: 'lc', name: 'Saint Lucian' },
  { value: 'vc', name: 'Saint Vincentian' },
  { value: 'ws', name: 'Samoan' },
  { value: 'sm', name: 'Sammarinese' },
  { value: 'st', name: 'São Toméan' },
  { value: 'sa', name: 'Saudi' },
  { value: 'sn', name: 'Senegalese' },
  { value: 'rs', name: 'Serbian' },
  { value: 'sc', name: 'Seychellois' },
  { value: 'sl', name: 'Sierra Leonean' },
  { value: 'sg', name: 'Singaporean' },
  { value: 'sk', name: 'Slovak' },
  { value: 'si', name: 'Slovenian' },
  { value: 'sb', name: 'Solomon Islander' },
  { value: 'so', name: 'Somali' },
  { value: 'za', name: 'South African' },
  { value: 'kr', name: 'South Korean' },
  { value: 'ss', name: 'South Sudanese' },
  { value: 'es', name: 'Spanish' },
  { value: 'lk', name: 'Sri Lankan' },
  { value: 'sd', name: 'Sudanese' },
  { value: 'sr', name: 'Surinamese' },
  { value: 'sz', name: 'Swazi' },
  { value: 'se', name: 'Swedish' },
  { value: 'ch', name: 'Swiss' },
  { value: 'sy', name: 'Syrian' },
  { value: 'tw', name: 'Taiwanese' },
  { value: 'tj', name: 'Tajik' },
  { value: 'tz', name: 'Tanzanian' },
  { value: 'th', name: 'Thai' },
  { value: 'tg', name: 'Togolese' },
  { value: 'to', name: 'Tongan' },
  { value: 'tt', name: 'Trinidadian/Tobagonian' },
  { value: 'tn', name: 'Tunisian' },
  { value: 'tr', name: 'Turk' },
  { value: 'tm', name: 'Turkmen' },
  { value: 'tv', name: 'Tuvaluan' },
  { value: 'ug', name: 'Ugandan' },
  { value: 'ua', name: 'Ukrainian' },
  { value: 'ae', name: 'Emirati' },
  { value: 'gb', name: 'British' },
  { value: 'us', name: 'American' },
  { value: 'uy', name: 'Uruguayan' },
  { value: 'uz', name: 'Uzbek or Uzbekistani' },
  { value: 'vu', name: 'Ni-Vanuatu' },
  { value: 'va', name: 'Vatican citizen' },
  { value: 've', name: 'Venezuelan' },
  { value: 'vn', name: 'Vietnamese' },
  { value: 'ye', name: 'Yemeni' },
  { value: 'zm', name: 'Zambian' },
  { value: 'zw', name: 'Zimbabwean' },
];

export const selectCountries: SelectOption[] = [
  { name: 'Afghanistan', value: 'AF' },
  { name: 'Albania', value: 'AL' },
  { name: 'Algeria', value: 'DZ' },
  { name: 'Andorra', value: 'AD' },
  { name: 'Angola', value: 'AO' },
  { name: 'Argentina', value: 'AR' },
  { name: 'Armenia', value: 'AM' },
  { name: 'Australia', value: 'AU' },
  { name: 'Austria', value: 'AT' },
  { name: 'Azerbaijan', value: 'AZ' },
  { name: 'Bahamas', value: 'BS' },
  { name: 'Bahrain', value: 'BH' },
  { name: 'Bangladesh', value: 'BD' },
  { name: 'Belarus', value: 'BY' },
  { name: 'Belgium', value: 'BE' },
  { name: 'Belize', value: 'BZ' },
  { name: 'Benin', value: 'BJ' },
  { name: 'Bhutan', value: 'BT' },
  { name: 'Bolivia', value: 'BO' },
  { name: 'Bosnia and Herzegovina', value: 'BA' },
  { name: 'Botswana', value: 'BW' },
  { name: 'Brazil', value: 'BR' },
  { name: 'Brunei', value: 'BN' },
  { name: 'Bulgaria', value: 'BG' },
  { name: 'Burkina Faso', value: 'BF' },
  { name: 'Burundi', value: 'BI' },
  { name: 'Cambodia', value: 'KH' },
  { name: 'Cameroon', value: 'CM' },
  { name: 'Canada', value: 'CA' },
  { name: 'Cape Verde', value: 'CV' },
  { name: 'Central African Republic', value: 'CF' },
  { name: 'Chad', value: 'TD' },
  { name: 'Chile', value: 'CL' },
  { name: 'China', value: 'CN' },
  { name: 'Colombia', value: 'CO' },
  { name: 'Comoros', value: 'KM' },
  { name: 'Costa Rica', value: 'CR' },
  { name: 'Croatia', value: 'HR' },
  { name: 'Cuba', value: 'CU' },
  { name: 'Cyprus', value: 'CY' },
  { name: 'Czech Republic', value: 'CZ' },
  { name: 'Democratic Republic of the Congo', value: 'CD' },
  { name: 'Denmark', value: 'DK' },
  { name: 'Djibouti', value: 'DJ' },
  { name: 'Dominica', value: 'DM' },
  { name: 'Dominican Republic', value: 'DO' },
  { name: 'Ecuador', value: 'EC' },
  { name: 'Egypt', value: 'EG' },
  { name: 'El Salvador', value: 'SV' },
  { name: 'Equatorial Guinea', value: 'GQ' },
  { name: 'Eritrea', value: 'ER' },
  { name: 'Estonia', value: 'EE' },
  { name: 'Eswatini', value: 'SZ' },
  { name: 'Ethiopia', value: 'ET' },
  { name: 'Fiji', value: 'FJ' },
  { name: 'Finland', value: 'FI' },
  { name: 'France', value: 'FR' },
  { name: 'Gabon', value: 'GA' },
  { name: 'Gambia', value: 'GM' },
  { name: 'Georgia', value: 'GE' },
  { name: 'Germany', value: 'DE' },
  { name: 'Ghana', value: 'GH' },
  { name: 'Greece', value: 'GR' },
  { name: 'Grenada', value: 'GD' },
  { name: 'Guatemala', value: 'GT' },
  { name: 'Guinea', value: 'GN' },
  { name: 'Guinea-Bissau', value: 'GW' },
  { name: 'Guyana', value: 'GY' },
  { name: 'Haiti', value: 'HT' },
  { name: 'Honduras', value: 'HN' },
  { name: 'Hungary', value: 'HU' },
  { name: 'Iceland', value: 'IS' },
  { name: 'India', value: 'IN' },
  { name: 'Indonesia', value: 'ID' },
  { name: 'Iran', value: 'IR' },
  { name: 'Iraq', value: 'IQ' },
  { name: 'Ireland', value: 'IE' },
  { name: 'Israel', value: 'IL' },
  { name: 'Italy', value: 'IT' },
  { name: 'Jamaica', value: 'JM' },
  { name: 'Japan', value: 'JP' },
  { name: 'Jordan', value: 'JO' },
  { name: 'Kazakhstan', value: 'KZ' },
  { name: 'Kenya', value: 'KE' },
  { name: 'Kiribati', value: 'KI' },
  { name: 'Kuwait', value: 'KW' },
  { name: 'Kyrgyzstan', value: 'KG' },
  { name: 'Laos', value: 'LA' },
  { name: 'Latvia', value: 'LV' },
  { name: 'Lebanon', value: 'LB' },
  { name: 'Lesotho', value: 'LS' },
  { name: 'Liberia', value: 'LR' },
  { name: 'Libya', value: 'LY' },
  { name: 'Liechtenstein', value: 'LI' },
  { name: 'Lithuania', value: 'LT' },
  { name: 'Luxembourg', value: 'LU' },
  { name: 'Madagascar', value: 'MG' },
  { name: 'Malawi', value: 'MW' },
  { name: 'Malaysia', value: 'MY' },
  { name: 'Maldives', value: 'MV' },
  { name: 'Mali', value: 'ML' },
  { name: 'Malta', value: 'MT' },
  { name: 'Mauritania', value: 'MR' },
  { name: 'Mauritius', value: 'MU' },
  { name: 'Mexico', value: 'MX' },
  { name: 'Moldova', value: 'MD' },
  { name: 'Monaco', value: 'MC' },
  { name: 'Mongolia', value: 'MN' },
  { name: 'Montenegro', value: 'ME' },
  { name: 'Morocco', value: 'MA' },
  { name: 'Mozambique', value: 'MZ' },
  { name: 'Myanmar', value: 'MM' },
  { name: 'Namibia', value: 'NA' },
  { name: 'Nepal', value: 'NP' },
  { name: 'Netherlands', value: 'NL' },
  { name: 'New Zealand', value: 'NZ' },
  { name: 'Nicaragua', value: 'NI' },
  { name: 'Niger', value: 'NE' },
  { name: 'Nigeria', value: 'NG' },
  { name: 'North Korea', value: 'KP' },
  { name: 'North Macedonia', value: 'MK' },
  { name: 'Norway', value: 'NO' },
  { name: 'Oman', value: 'OM' },
  { name: 'Pakistan', value: 'PK' },
  { name: 'Palestine', value: 'PS' },
  { name: 'Panama', value: 'PA' },
  { name: 'Papua New Guinea', value: 'PG' },
  { name: 'Paraguay', value: 'PY' },
  { name: 'Peru', value: 'PE' },
  { name: 'Philippines', value: 'PH' },
  { name: 'Poland', value: 'PL' },
  { name: 'Portugal', value: 'PT' },
  { name: 'Qatar', value: 'QA' },
  { name: 'Romania', value: 'RO' },
  { name: 'Russia', value: 'RU' },
  { name: 'Rwanda', value: 'RW' },
  { name: 'Saudi Arabia', value: 'SA' },
  { name: 'Senegal', value: 'SN' },
  { name: 'Serbia', value: 'RS' },
  { name: 'Seychelles', value: 'SC' },
  { name: 'Sierra Leone', value: 'SL' },
  { name: 'Singapore', value: 'SG' },
  { name: 'Slovakia', value: 'SK' },
  { name: 'Slovenia', value: 'SI' },
  { name: 'Solomon Islands', value: 'SB' },
  { name: 'Somalia', value: 'SO' },
  { name: 'South Africa', value: 'ZA' },
  { name: 'South Korea', value: 'KR' },
  { name: 'South Sudan', value: 'SS' },
  { name: 'Spain', value: 'ES' },
  { name: 'Sri Lanka', value: 'LK' },
  { name: 'Sudan', value: 'SD' },
  { name: 'Suriname', value: 'SR' },
  { name: 'Sweden', value: 'SE' },
  { name: 'Switzerland', value: 'CH' },
  { name: 'Syria', value: 'SY' },
  { name: 'Taiwan', value: 'TW' },
  { name: 'Tajikistan', value: 'TJ' },
  { name: 'Tanzania', value: 'TZ' },
  { name: 'Thailand', value: 'TH' },
  { name: 'Timor-Leste', value: 'TL' },
  { name: 'Togo', value: 'TG' },
  { name: 'Tonga', value: 'TO' },
  { name: 'Trinidad and Tobago', value: 'TT' },
  { name: 'Tunisia', value: 'TN' },
  { name: 'Turkey', value: 'TR' },
  { name: 'Turkmenistan', value: 'TM' },
  { name: 'Tuvalu', value: 'TV' },
  { name: 'Uganda', value: 'UG' },
  { name: 'Ukraine', value: 'UA' },
  { name: 'United Arab Emirates', value: 'AE' },
  { name: 'United Kingdom', value: 'GB' },
  { name: 'United States', value: 'US' },
  { name: 'Uruguay', value: 'UY' },
  { name: 'Uzbekistan', value: 'UZ' },
  { name: 'Vanuatu', value: 'VU' },
  { name: 'Vatican City', value: 'VA' },
  { name: 'Venezuela', value: 'VE' },
  { name: 'Vietnam', value: 'VN' },
  { name: 'Yemen', value: 'YE' },
  { name: 'Zambia', value: 'ZM' },
  { name: 'Zimbabwe', value: 'ZW' },
];
