import { SelectOption } from 'app/shared/components/atoms/select/select.component';

export const selectNationality: SelectOption[] = [
  { value: 'af', name: 'Afghan' },
  { value: 'al', name: 'Albanian' },
  { value: 'dz', name: 'Algerian' },
  { value: 'ad', name: 'Andorran' },
  { value: 'ao', name: 'Angolan' },
  { value: 'ag', name: 'Antiguan/Barbudan' },
  { value: 'ar', name: 'Argentine' },
  { value: 'am', name: 'Armenian' },
  { value: 'au', name: 'Australian' },
  { value: 'at', name: 'Austrian' },
  { value: 'az', name: 'Azerbaijani' },
  { value: 'bs', name: 'Bahamian' },
  { value: 'bh', name: 'Bahraini' },
  { value: 'bd', name: 'Bangladeshi' },
  { value: 'bb', name: 'Barbadian' },
  { value: 'by', name: 'Belarusian' },
  { value: 'be', name: 'Belgian' },
  { value: 'bz', name: 'Belizean' },
  { value: 'bj', name: 'Beninese' },
  { value: 'bt', name: 'Bhutanese' },
  { value: 'bo', name: 'Bolivian' },
  { value: 'ba', name: 'Bosnian/Herzegovinian' },
  { value: 'bw', name: 'Botswanan' },
  { value: 'br', name: 'Brazilian' },
  { value: 'bn', name: 'Bruneian' },
  { value: 'bg', name: 'Bulgarian' },
  { value: 'bf', name: 'Burkinabe' },
  { value: 'bi', name: 'Burundian' },
  { value: 'kh', name: 'Cambodian' },
  { value: 'cm', name: 'Cameroonian' },
  { value: 'ca', name: 'Canadian' },
  { value: 'cv', name: 'Cape Verdean' },
  { value: 'cf', name: 'Central African' },
  { value: 'td', name: 'Chadian' },
  { value: 'cl', name: 'Chilean' },
  { value: 'cn', name: 'Chinese' },
  { value: 'co', name: 'Colombian' },
  { value: 'km', name: 'Comoran' },
  { value: 'cg', name: 'Congolese' },
  { value: 'cd', name: 'Congolese (DRC)' },
  { value: 'cr', name: 'Costa Rican' },
  { value: 'ci', name: 'Ivorian' },
  { value: 'hr', name: 'Croatian' },
  { value: 'cu', name: 'Cuban' },
  { value: 'cy', name: 'Cypriot' },
  { value: 'cz', name: 'Czech' },
  { value: 'dk', name: 'Danish' },
  { value: 'dj', name: 'Djiboutian' },
  { value: 'dm', name: 'Dominican (DM)' },
  { value: 'do', name: 'Dominican (DO)' },
  { value: 'tl', name: 'Timorese' },
  { value: 'ec', name: 'Ecuadorian' },
  { value: 'eg', name: 'Egyptian' },
  { value: 'sv', name: 'Salvadoran' },
  { value: 'gq', name: 'Equatorial Guinean' },
  { value: 'er', name: 'Eritrean' },
  { value: 'ee', name: 'Estonian' },
  { value: 'et', name: 'Ethiopian' },
  { value: 'fj', name: 'Fijian' },
  { value: 'fi', name: 'Finnish' },
  { value: 'fr', name: 'French' },
  { value: 'ga', name: 'Gabonese' },
  { value: 'gm', name: 'Gambian' },
  { value: 'ge', name: 'Georgian' },
  { value: 'de', name: 'German' },
  { value: 'gh', name: 'Ghanaian' },
  { value: 'gr', name: 'Greek' },
  { value: 'gd', name: 'Grenadian' },
  { value: 'gt', name: 'Guatemalan' },
  { value: 'gn', name: 'Guinean' },
  { value: 'gw', name: 'Bissau-Guinean' },
  { value: 'gy', name: 'Guyanese' },
  { value: 'ht', name: 'Haitian' },
  { value: 'hn', name: 'Honduran' },
  { value: 'hu', name: 'Hungarian' },
  { value: 'is', name: 'Icelander' },
  { value: 'in', name: 'Indian' },
  { value: 'id', name: 'Indonesian' },
  { value: 'ir', name: 'Iranian' },
  { value: 'iq', name: 'Iraqi' },
  { value: 'ie', name: 'Irish' },
  { value: 'il', name: 'Israeli' },
  { value: 'it', name: 'Italian' },
  { value: 'jm', name: 'Jamaican' },
  { value: 'jp', name: 'Japanese' },
  { value: 'jo', name: 'Jordanian' },
  { value: 'kz', name: 'Kazakhstani' },
  { value: 'ke', name: 'Kenyan' },
  { value: 'ki', name: 'I-Kiribati' },
  { value: 'xk', name: 'Kosovar' },
  { value: 'kw', name: 'Kuwaiti' },
  { value: 'kg', name: 'Kyrgyz or Kyrgyzstani' },
  { value: 'la', name: 'Lao or Laotian' },
  { value: 'lv', name: 'Latvian' },
  { value: 'lb', name: 'Lebanese' },
  { value: 'ls', name: 'Mosotho (Basotho plural)' },
  { value: 'lr', name: 'Liberian' },
  { value: 'ly', name: 'Libyan' },
  { value: 'li', name: 'Liechtensteiner' },
  { value: 'lt', name: 'Lithuanian' },
  { value: 'lu', name: 'Luxembourger' },
  { value: 'mk', name: 'Macedonian' },
  { value: 'mg', name: 'Malagasy' },
  { value: 'mw', name: 'Malawian' },
  { value: 'my', name: 'Malaysian' },
  { value: 'mv', name: 'Maldivian' },
  { value: 'ml', name: 'Malian' },
  { value: 'mt', name: 'Maltese' },
  { value: 'mh', name: 'Marshallese' },
  { value: 'mr', name: 'Mauritanian' },
  { value: 'mu', name: 'Mauritian' },
  { value: 'mx', name: 'Mexican' },
  { value: 'fm', name: 'Micronesian' },
  { value: 'md', name: 'Moldovan' },
  { value: 'mc', name: 'Monégasque' },
  { value: 'mn', name: 'Mongolian' },
  { value: 'me', name: 'Montenegrin' },
  { value: 'ma', name: 'Moroccan' },
  { value: 'mz', name: 'Mozambican' },
  { value: 'mm', name: 'Burmese' },
  { value: 'na', name: 'Namibian' },
  { value: 'nr', name: 'Nauruan' },
  { value: 'np', name: 'Nepali' },
  { value: 'nl', name: 'Dutch' },
  { value: 'nz', name: 'New Zealander' },
  { value: 'ni', name: 'Nicaraguan' },
  { value: 'ne', name: 'Nigerien' },
  { value: 'ng', name: 'Nigerian' },
  { value: 'kp', name: 'North Korean' },
  { value: 'no', name: 'Norwegian' },
  { value: 'om', name: 'Omani' },
  { value: 'pk', name: 'Pakistani' },
  { value: 'pw', name: 'Palauan' },
  { value: 'ps', name: 'Palestinian' },
  { value: 'pa', name: 'Panamanian' },
  { value: 'pg', name: 'Papua New Guinean' },
  { value: 'py', name: 'Paraguayan' },
  { value: 'pe', name: 'Peruvian' },
  { value: 'ph', name: 'Filipino' },
  { value: 'pl', name: 'Polish' },
  { value: 'pt', name: 'Portuguese' },
  { value: 'qa', name: 'Qatari' },
  { value: 'ro', name: 'Romanian' },
  { value: 'ru', name: 'Russian' },
  { value: 'rw', name: 'Rwandan' },
  { value: 'kn', name: 'Kittitian and Nevisian' },
  { value: 'lc', name: 'Saint Lucian' },
  { value: 'vc', name: 'Saint Vincentian' },
  { value: 'ws', name: 'Samoan' },
  { value: 'sm', name: 'Sammarinese' },
  { value: 'st', name: 'São Toméan' },
  { value: 'sa', name: 'Saudi' },
  { value: 'sn', name: 'Senegalese' },
  { value: 'rs', name: 'Serbian' },
  { value: 'sc', name: 'Seychellois' },
  { value: 'sl', name: 'Sierra Leonean' },
  { value: 'sg', name: 'Singaporean' },
  { value: 'sk', name: 'Slovak' },
  { value: 'si', name: 'Slovenian' },
  { value: 'sb', name: 'Solomon Islander' },
  { value: 'so', name: 'Somali' },
  { value: 'za', name: 'South African' },
  { value: 'kr', name: 'South Korean' },
  { value: 'ss', name: 'South Sudanese' },
  { value: 'es', name: 'Spanish' },
  { value: 'lk', name: 'Sri Lankan' },
  { value: 'sd', name: 'Sudanese' },
  { value: 'sr', name: 'Surinamese' },
  { value: 'sz', name: 'Swazi' },
  { value: 'se', name: 'Swedish' },
  { value: 'ch', name: 'Swiss' },
  { value: 'sy', name: 'Syrian' },
  { value: 'tw', name: 'Taiwanese' },
  { value: 'tj', name: 'Tajik' },
  { value: 'tz', name: 'Tanzanian' },
  { value: 'th', name: 'Thai' },
  { value: 'tg', name: 'Togolese' },
  { value: 'to', name: 'Tongan' },
  { value: 'tt', name: 'Trinidadian/Tobagonian' },
  { value: 'tn', name: 'Tunisian' },
  { value: 'tr', name: 'Turk' },
  { value: 'tm', name: 'Turkmen' },
  { value: 'tv', name: 'Tuvaluan' },
  { value: 'ug', name: 'Ugandan' },
  { value: 'ua', name: 'Ukrainian' },
  { value: 'ae', name: 'Emirati' },
  { value: 'gb', name: 'British' },
  { value: 'us', name: 'American' },
  { value: 'uy', name: 'Uruguayan' },
  { value: 'uz', name: 'Uzbek or Uzbekistani' },
  { value: 'vu', name: 'Ni-Vanuatu' },
  { value: 'va', name: 'Vatican citizen' },
  { value: 've', name: 'Venezuelan' },
  { value: 'vn', name: 'Vietnamese' },
  { value: 'ye', name: 'Yemeni' },
  { value: 'zm', name: 'Zambian' },
  { value: 'zw', name: 'Zimbabwean' },
  { value: 'ot', name: 'Other' },
];
