package de.tum.cit.aet.core.constants;

public enum ErrorCode {
    ACCESS_DENIED,
    EMAIL_TEMPLATE_ERROR,
    ENTITY_NOT_FOUND,
    INTERNAL_ERROR,
    INVALID_PARAMETER,
    TEMPLATE_ERROR,
    MAILING_ERROR,
    OPERATION_NOT_ALLOWED,
    RESOURCE_ALREADY_EXISTS,
    UNAUTHORIZED,
    UPLOAD_FAILED,
    VALIDATION_ERROR,
}
