package de.tum.cit.aet.core.service.export.admin;

import de.tum.cit.aet.application.domain.Application;
import de.tum.cit.aet.core.util.PDFBuilder;
import de.tum.cit.aet.interview.domain.InterviewSlot;
import de.tum.cit.aet.interview.domain.Interviewee;
import de.tum.cit.aet.interview.domain.enumeration.AssessmentRating;
import de.tum.cit.aet.job.domain.Job;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import org.springframework.core.io.Resource;

/**
 * Builds a small one-page summary PDF for an {@link Interviewee} record. Used by
 * the admin bulk export so each applicant folder that has interview data on
 * file gets a human-readable {@code interview_summary.pdf} alongside the JSON
 * dump in the {@code interview/} subfolder.
 *
 * <p>Self-contained on top of the project's existing {@link PDFBuilder} (iText
 * html2pdf); intentionally not added to {@code PDFExportService} so it stays
 * scoped to the admin export package.
 */
final class AdminInterviewPdf {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    private static final DateTimeFormatter TIME_FMT = DateTimeFormatter.ofPattern("HH:mm");
    private static final DateTimeFormatter DATE_TIME_FMT = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
    private static final ZoneId LOCAL_ZONE = ZoneId.of("Europe/Berlin");

    private AdminInterviewPdf() {}

    /**
     * Builds a PDF resource summarizing the given interviewee. Returns the bytes
     * wrapped in a Spring {@link Resource} so the caller can stream them
     * straight into a ZIP entry.
     *
     * @param interviewee the interviewee whose data should be exported
     * @param app         the linked application (used for the applicant header)
     * @param job         the job the application is for (used for the title)
     * @return a one-page interview summary PDF
     */
    static Resource build(Interviewee interviewee, Application app, Job job) {
        String jobTitle = job == null || job.getTitle() == null ? "(unknown job)" : job.getTitle();
        String applicantName = formatApplicantName(app);

        PDFBuilder builder = new PDFBuilder("Interview – " + jobTitle);

        builder.addHeaderItem("Applicant: " + applicantName);
        builder.addHeaderItem("Status: " + formatRating(interviewee.getRating()));
        if (interviewee.getLastInvited() != null) {
            builder.addHeaderItem("Invited: " + formatInstant(interviewee.getLastInvited()));
        }

        // ---------- Schedule section ----------
        builder.startSectionGroup("Schedule");
        List<InterviewSlot> slots = interviewee.getSlots() == null ? List.of() : interviewee.getSlots();
        if (slots.isEmpty()) {
            builder.startInfoSection("No slot scheduled").addSectionContent("This applicant has not been booked into a slot yet.");
        } else {
            int idx = 1;
            for (InterviewSlot slot : slots) {
                String sectionTitle = slots.size() == 1 ? "Slot" : "Slot " + idx++;
                builder.startInfoSection(sectionTitle);
                builder.addSectionData("Date", formatInstantDate(slot.getStartDateTime()));
                builder.addSectionData(
                    "Time",
                    formatInstantTime(slot.getStartDateTime()) + " – " + formatInstantTime(slot.getEndDateTime())
                );
                builder.addSectionData("Location", nullSafe(slot.getLocation()));
                if (slot.getStreamLink() != null && !slot.getStreamLink().isBlank()) {
                    builder.addSectionData("Stream link", slot.getStreamLink());
                }
                builder.addSectionData("Booked", Boolean.TRUE.equals(slot.getIsBooked()) ? "yes" : "no");
            }
        }

        // ---------- Assessment section ----------
        builder.startSectionGroup("Assessment");
        builder.startInfoSection("Rating").addSectionData("Rating", formatRating(interviewee.getRating()));
        builder.startInfoSection("Notes").addSectionContent(nullSafeNotes(interviewee.getAssessmentNotes()));

        // ---------- Footer ----------
        builder.setMetadata("This document was generated on " + LocalDateTime.now().format(DATE_TIME_FMT) + " by ");
        builder.setMetadataEnd("Generated by TUMApply admin export.");
        builder.setPageLabels("Page", "of");

        return builder.build();
    }

    // ----------------------------- formatting helpers -----------------------------

    private static String formatApplicantName(Application app) {
        if (app == null) {
            return "(unknown applicant)";
        }
        String last = app.getApplicantLastName();
        String first = app.getApplicantFirstName();
        String composed = ((last == null ? "" : last) + ", " + (first == null ? "" : first)).trim();
        return composed.replaceAll("^,\\s*|,\\s*$", "").isBlank() ? "(unknown applicant)" : composed;
    }

    private static String formatRating(AssessmentRating rating) {
        return rating == null ? "Not yet rated" : rating.name() + " (" + rating.getValue() + ")";
    }

    private static String formatInstant(Instant instant) {
        return instant == null ? "-" : DATE_TIME_FMT.format(instant.atZone(LOCAL_ZONE).toLocalDateTime());
    }

    private static String formatInstantDate(Instant instant) {
        return instant == null ? "-" : DATE_FMT.format(instant.atZone(LOCAL_ZONE).toLocalDateTime());
    }

    private static String formatInstantTime(Instant instant) {
        return instant == null ? "-" : TIME_FMT.format(instant.atZone(LOCAL_ZONE).toLocalDateTime());
    }

    private static String nullSafe(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }

    private static String nullSafeNotes(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }
}
