package de.tum.cit.aet.core.service.export.admin;

import java.util.Map;

/**
 * Hard-coded English label set used when generating PDFs from inside the admin
 * bulk export. The user-facing PDF endpoints normally receive their labels from
 * the Angular frontend (so they can follow the user's selected language), but
 * admin exports run server-side from a scheduled job and have no request locale
 * — we ship a single, stable English label set instead.
 *
 * <p>Keep this in sync with the keys read by
 * {@link de.tum.cit.aet.core.service.PDFExportService}.
 */
final class AdminPdfLabels {

    private AdminPdfLabels() {}

    /** Labels needed by {@code PDFExportService.exportJobToPDF}. */
    static Map<String, String> forJob() {
        return Map.ofEntries(
            Map.entry("lang", "en"),
            Map.entry("jobBy", "Job by "),
            Map.entry("forJob", " for the position "),
            Map.entry("status", "Status: "),
            Map.entry("overview", "Position Overview"),
            Map.entry("supervisor", "Supervisor"),
            Map.entry("location", "Location"),
            Map.entry("subjectArea", "Subject area:"),
            Map.entry("researchArea", "Research area:"),
            Map.entry("workload", "Workload:"),
            Map.entry("hoursPerWeek", "h/week"),
            Map.entry("duration", "Contract duration:"),
            Map.entry("years", "years"),
            Map.entry("fundingType", "Funding type:"),
            Map.entry("startDate", "Start date:"),
            Map.entry("endDate", "Application deadline:"),
            Map.entry("jobDetails", "Job Details"),
            Map.entry("researchGroup", "Research Group"),
            Map.entry("contactDetails", "Contact details"),
            Map.entry("address", "Address"),
            Map.entry("email", "Email"),
            Map.entry("website", "Website"),
            Map.entry("thisDocumentWasGeneratedOn", "This document was generated on "),
            Map.entry("byUser", " by "),
            Map.entry("usingTumapply", " using TUMApply."),
            Map.entry("metaEndText", "Generated by TUMApply admin export."),
            Map.entry("page", "Page"),
            Map.entry("of", "of"),
            Map.entry("jobPdfEnding", "job")
        );
    }

    /** Labels needed by {@code PDFExportService.exportInterviewToPDF}. */
    static Map<String, String> forInterview() {
        return Map.ofEntries(
            Map.entry("interviewHeading", "Interview – "),
            Map.entry("applicantInfo", "Applicant"),
            Map.entry("status", "Status: "),
            Map.entry("invitedAt", "Invited: "),
            Map.entry("interviewSchedule", "Schedule"),
            Map.entry("interviewSlot", "Slot"),
            Map.entry("interviewDate", "Date"),
            Map.entry("interviewTime", "Time"),
            Map.entry("interviewLocation", "Location"),
            Map.entry("interviewStreamLink", "Stream link"),
            Map.entry("interviewBooked", "Booked"),
            Map.entry("interviewNoSlotTitle", "No slot scheduled"),
            Map.entry("interviewNoSlotMessage", "This applicant has not been booked into a slot yet."),
            Map.entry("interviewAssessment", "Assessment"),
            Map.entry("interviewRating", "Rating"),
            Map.entry("interviewNotes", "Notes"),
            Map.entry("interviewNotRated", "Not yet rated"),
            Map.entry("yes", "yes"),
            Map.entry("no", "no"),
            Map.entry("thisDocumentWasGeneratedOn", "This document was generated on "),
            Map.entry("byUser", " by "),
            Map.entry("usingTumapply", " using TUMApply."),
            Map.entry("metaEndText", "Generated by TUMApply admin export."),
            Map.entry("page", "Page"),
            Map.entry("of", "of")
        );
    }

    /** Labels needed by {@code PDFExportService.exportApplicationToPDF}. */
    static Map<String, String> forApplication() {
        return Map.ofEntries(
            Map.entry("lang", "en"),
            Map.entry("headline", "Application for "),
            Map.entry("applicationBy", "Application by "),
            Map.entry("forPosition", " for the position "),
            Map.entry("status", "Status: "),
            Map.entry("overview", "Position Overview"),
            Map.entry("supervisor", "Supervisor"),
            Map.entry("researchGroup", "Research Group"),
            Map.entry("location", "Location"),
            Map.entry("subjectArea", "Subject area:"),
            Map.entry("researchArea", "Research area:"),
            Map.entry("workload", "Workload:"),
            Map.entry("hoursPerWeek", "h/week"),
            Map.entry("duration", "Contract duration:"),
            Map.entry("years", "years"),
            Map.entry("fundingType", "Funding type:"),
            Map.entry("startDate", "Start date:"),
            Map.entry("endDate", "Application deadline:"),
            Map.entry("jobDetails", "Job Details"),
            Map.entry("personalStatements", "Personal Statements"),
            Map.entry("motivation", "Motivation"),
            Map.entry("skills", "Special Skills"),
            Map.entry("researchExperience", "Research Experience"),
            Map.entry("personalInformation", "Personal Information"),
            Map.entry("applicantInfo", "Applicant Information"),
            Map.entry("name", "Name"),
            Map.entry("email", "Email"),
            Map.entry("phoneNumber", "Phone number"),
            Map.entry("desiredStartDate", "Desired start date"),
            Map.entry("gender", "Gender"),
            Map.entry("nationality", "Nationality"),
            Map.entry("address", "Address"),
            Map.entry("country", "Country"),
            Map.entry("website", "Website"),
            Map.entry("linkedIn", "LinkedIn"),
            Map.entry("bachelorInfo", "Bachelor's Degree"),
            Map.entry("masterInfo", "Master's Degree"),
            Map.entry("degreeName", "Name"),
            Map.entry("university", "University"),
            Map.entry("grade", "Grade"),
            Map.entry("application", "application"),
            Map.entry("thisDocumentWasGeneratedOn", "This document was generated on "),
            Map.entry("byUser", " by "),
            Map.entry("usingTumapply", " using TUMApply."),
            Map.entry("metaEndText", "Generated by TUMApply admin export."),
            Map.entry("page", "Page"),
            Map.entry("of", "of")
        );
    }
}
