import { definePreset } from '@primeng/themes';
import Lara from '@primeng/themes/lara';

export const TUMApplyPreset = definePreset(Lara, {
  semantic: {
    primary: {
      50: '#D6E6FA',
      100: '#B1D1F6',
      200: '#63A2EE',
      300: '#1872DD',
      400: '#10498F',
      500: '#072140',
      600: '#061A33',
      700: '#041325',
      800: '#030E1C',
      900: '#02070E',
      950: '#010205',
    },
    secondary: {
      50: '#DFECFC',
      100: '#BFD9F8',
      200: '#83B6F2',
      300: '#428FEB',
      400: '#176DD4',
      500: '#104D95',
      600: '#0D3E78',
      700: '#092D58',
      800: '#061F3C',
      900: '#030E1C',
      950: '#01070E',
    },
    tertiary: {
      50: '#E8F1FD',
      100: '#D0E4FB',
      200: '#A2C8F6',
      300: '#78B0F3',
      400: '#4994EE',
      500: '#1A79EA',
      600: '#1261C0',
      700: '#0D4991',
      800: '#092F5D',
      900: '#04182F',
      950: '#020C17',
    },
    success: {
      50: '#E6FAEE',
      100: '#D0F5E1',
      200: '#A2ECC2',
      300: '#73E2A4',
      400: '#45D985',
      500: '#27BE69',
      600: '#1F9854',
      700: '#17723F',
      800: '#104C2A',
      900: '#082615',
      950: '#031109',
    },
    danger: {
      50: '#FEECEE',
      100: '#FCD9DE',
      200: '#FAB3BD',
      300: '#F78C9C',
      400: '#F5667A',
      500: '#F2415A',
      600: '#E5102E',
      700: '#AC0C22',
      800: '#730817',
      900: '#39040B',
      950: '#1D0206',
    },
    warn: {
      50: '#FFF8E5',
      100: '#FFF3D1',
      200: '#FFE59E',
      300: '#FFD970',
      400: '#FFCB3D',
      500: '#FFBF0F',
      600: '#D69D00',
      700: '#A37800',
      800: '#6B4F00',
      900: '#382900',
      950: '#1A1300',
    },
    info: {
      50: '#EBEFFF',
      100: '#D6E0FF',
      200: '#A8BDFF',
      300: '#809DFF',
      400: '#527AFF',
      500: '#295BFF',
      600: '#0037EB',
      700: '#002AB3',
      800: '#001B75',
      900: '#000E3D',
      950: '#00071F',
    },
    neutral: {
      50: '#F7F7F8',
      100: '#E6E6E6',
      200: '#D4D4D5',
      300: '#C0C0C1',
      400: '#AEAEAF',
      500: '#8D8D8F',
      600: '#676769',
      700: '#414144',
      800: '#343537',
      850: '#212121',
      900: '#1A1B1E',
      950: '#010205',
    },
    base: {
      white: '#ffffff',
      black: '#000000',
    },
    accent: {
      50: '#FFF3E9',
      100: '#FFE3CC',
      200: '#FFD0A8',
      300: '#FEB27D',
      400: '#F29B5F',
      500: '#E37222',
      600: '#C55E1A',
      700: '#A04A14',
      800: '#7B370F',
      900: '#522408',
      950: '#2B1304',
    },
    colorScheme: {
      light: {
        text: {
          primary: '{neutral.950}',
          secondary: '{neutral.700}',
          tertiary: '{neutral.500}',
          disabled: '{neutral.600}',
          onPrimary: '{base.white}',
          onSecondary: '{base.white}',
          onAccent: '{base.white}',
          onSuccess: '{base.black}',
          onDanger: '{base.black}',
          onWarn: '{base.black}',
          onInfo: '{base.black}',
        },
        primary: {
          color: '{primary.300}',
          inverseColor: '{text.onPrimary}',
          hoverColor: '{primary.600}',
          activeColor: '{primary.700}',
          disabledColor: '{primary.200}',
        },
        secondary: {
          color: '{secondary.300}',
          inverseColor: '{text.onSecondary}',
          hoverColor: '{secondary.600}',
          activeColor: '{secondary.700}',
          disabledColor: '{secondary.200}',
        },
        accent: {
          color: '{accent.400}',
          inverseColor: '{text.onAccent}',
          hoverColor: '{accent.500}',
          activeColor: '{accent.600}',
          disabledColor: '{accent.200}',
        },
        highlight: {
          background: '{primary.950}',
          focusBackground: '{primary.700}',
          color: '{base.white}',
          focusColor: '{base.white}',
        },
        success: {
          color: '{success.500}',
          inverseColor: '{text.onSuccess}',
          hoverColor: '{success.600}',
          activeColor: '{success.700}',
          disabledColor: '{success.200}',
        },
        warn: {
          color: '{warn.500}',
          inverseColor: '{text.onWarn}',
          hoverColor: '{warn.600}',
          activeColor: '{warn.700}',
          disabledColor: '{warn.200}',
        },
        danger: {
          color: '{danger.500}',
          inverseColor: '{text.onDanger}',
          hoverColor: '{danger.600}',
          activeColor: '{danger.700}',
          disabledColor: '{danger.200}',
        },
        info: {
          color: '{info.500}',
          inverseColor: '{text.onInfo}',
          hoverColor: '{info.600}',
          activeColor: '{info.700}',
          disabledColor: '{info.200}',
        },
        background: {
          default: '{base.white}',
          surface: '{neutral.50}',
          surfaceAlt: '{neutral.100}',
          special: '{tertiary.50}',
          disabled: '{neutral.200}',
          footer: '{neutral.100}',
        },
        border: {
          default: '{neutral.300}',
        },
        divider: {
          default: '{neutral.200}',
        },
      },
      dark: {
        text: {
          primary: '{neutral.50}',
          secondary: '{neutral.200}',
          tertiary: '{neutral.400}',
          disabled: '{neutral.200}',
          onPrimary: '{base.white}',
          onSecondary: '{base.white}',
          onAccent: '{base.white}',
          onSuccess: '{base.black}',
          onDanger: '{base.black}',
          onWarn: '{base.black}',
          onInfo: '{base.white}',
        },
        primary: {
          color: '{primary.300}',
          inverseColor: '{text.onPrimary}',
          hoverColor: '{primary.200}',
          activeColor: '{primary.100}',
          disabledColor: '{primary.50}',
        },
        secondary: {
          color: '{secondary.500}',
          inverseColor: '{text.onSecondary}',
          hoverColor: '{secondary.600}',
          activeColor: '{secondary.700}',
          disabledColor: '{secondary.800}',
        },
        accent: {
          color: '{accent.300}',
          inverseColor: '{text.onAccent}',
          hoverColor: '{accent.200}',
          activeColor: '{accent.100}',
          disabledColor: '{accent.800}',
        },
        highlight: {
          background: '{primary.50}',
          focusBackground: '{primary.300}',
          color: '{base.black}',
          focusColor: '{base.black}',
        },
        success: {
          color: '{success.500}',
          inverseColor: '{text.onSuccess}',
          hoverColor: '{success.600}',
          activeColor: '{success.700}',
          disabledColor: '{success.800}',
        },
        warn: {
          color: '{warn.500}',
          inverseColor: '{text.onWarn}',
          hoverColor: '{warn.600}',
          activeColor: '{warn.700}',
          disabledColor: '{warn.800}',
        },
        danger: {
          color: '{danger.500}',
          inverseColor: '{text.onDanger}',
          hoverColor: '{danger.600}',
          activeColor: '{danger.700}',
          disabledColor: '{danger.800}',
        },
        info: {
          color: '{info.500}',
          inverseColor: '{text.onInfo}',
          hoverColor: '{info.600}',
          activeColor: '{info.700}',
          disabledColor: '{info.800}',
        },
        background: {
          default: '{neutral.900}',
          surface: '{neutral.800}',
          surfaceAlt: '{neutral.800}',
          special: '{tertiary.900}',
          disabled: '{neutral.700}',
          footer: '{neutral.850}',
        },
        border: {
          default: '{neutral.600}',
        },
        divider: {
          default: '{neutral.700}',
        },
      },
    },
  },
  components: {
    button: {
      root: {
        borderRadius: '0.75rem',
        fontWeight: '100',
        badgeSize: '1rem',
        borderWidth: '3rem',
        transitionDuration: '{form.field.transition.duration}',
      },
      colorScheme: {
        light: {
          root: {
            primary: {
              background: '{primary.color}',
              text: '{primary.inverseColor}',
              hoverBackground: '{primary.hoverColor}',
              activeBackground: '{primary.activeColor}',
              disabledBackground: '{primary.disabledColor}',
              disabledText: '{text.disabled}',
            },
            secondary: {
              background: '{secondary.color}',
              text: '{secondary.inverseColor}',
              hoverBackground: '{secondary.hoverColor}',
              activeBackground: '{secondary.activeColor}',
              disabledBackground: '{secondary.disabledColor}',
              disabledText: '{text.disabled}',
            },
            success: {
              background: '{success.color}',
              text: '{success.inverseColor}',
              hoverBackground: '{success.hoverColor}',
              activeBackground: '{success.activeColor}',
              disabledBackground: '{success.disabledColor}',
              disabledText: '{text.disabled}',
            },
            danger: {
              background: '{danger.color}',
              text: '{danger.inverseColor}',
              hoverBackground: '{danger.hoverColor}',
              activeBackground: '{danger.activeColor}',
              disabledBackground: '{danger.disabledColor}',
              disabledText: '{text.disabled}',
            },
            warn: {
              background: '{warn.color}',
              text: '{warn.inverseColor}',
              hoverBackground: '{warn.hoverColor}',
              activeBackground: '{warn.activeColor}',
              disabledBackground: '{warn.disabledColor}',
              disabledText: '{text.disabled}',
            },
            info: {
              background: '{info.color}',
              text: '{info.inverseColor}',
              hoverBackground: '{info.hoverColor}',
              activeBackground: '{info.activeColor}',
              disabledBackground: '{info.disabledColor}',
              disabledText: '{text.disabled}',
            },
            accent: {
              background: '{accent.color}',
              text: '{accent.inverseColor}',
              hoverBackground: '{accent.hoverColor}',
              activeBackground: '{accent.activeColor}',
              disabledBackground: '{accent.disabledColor}',
              disabledText: '{text.disabled}',
            },
          },
          outlined: {
            primary: {
              hoverBackground: '{primary.50}',
              activeBackground: '{primary.100}',
              borderColor: '{primary.200}',
              color: '{primary.color}',
            },
            secondary: {
              hoverBackground: '{secondary.50}',
              activeBackground: '{secondary.100}',
              borderColor: '{secondary.200}',
              color: '{secondary.500}',
            },
            success: {
              hoverBackground: '{success.50}',
              activeBackground: '{success.100}',
              borderColor: '{success.200}',
              color: '{success.500}',
            },
            info: {
              hoverBackground: '{info.50}',
              activeBackground: '{info.100}',
              borderColor: '{info.200}',
              color: '{info.500}',
            },
            warn: {
              hoverBackground: '{warn.50}',
              activeBackground: '{warn.100}',
              borderColor: '{warn.200}',
              color: '{warn.500}',
            },
            help: {
              hoverBackground: '{purple.50}',
              activeBackground: '{purple.100}',
              borderColor: '{purple.200}',
              color: '{purple.500}',
            },
            danger: {
              hoverBackground: '{danger.50}',
              activeBackground: '{danger.100}',
              borderColor: '{danger.200}',
              color: '{danger.500}',
            },
            contrast: {
              hoverBackground: '{surface.50}',
              activeBackground: '{surface.100}',
              borderColor: '{surface.700}',
              color: '{surface.950}',
            },
            plain: {
              hoverBackground: '{surface.50}',
              activeBackground: '{surface.100}',
              borderColor: '{surface.200}',
              color: '{surface.700}',
            },
          },
          text: {
            primary: {
              hoverBackground: '{primary.50}',
              activeBackground: '{primary.100}',
              color: '{primary.color}',
            },
            secondary: {
              hoverBackground: '{secondary.100}',
              activeBackground: '{secondary.200}',
              color: '{secondary.600}',
            },
            success: {
              hoverBackground: '{success.50}',
              activeBackground: '{success.100}',
              color: '{success.500}',
            },
            info: {
              hoverBackground: '{info.50}',
              activeBackground: '{info.100}',
              color: '{info.500}',
            },
            warn: {
              hoverBackground: '{warn.50}',
              activeBackground: '{warn.100}',
              color: '{warn.500}',
            },
            neutral: {
              hoverBackground: '{neutral.50}',
              activeBackground: '{neutral.100}',
              color: '{neutral.500}',
            },
            danger: {
              hoverBackground: '{danger.50}',
              activeBackground: '{danger.100}',
              color: '{danger.500}',
            },
            contrast: {
              hoverBackground: '{surface.50}',
              activeBackground: '{surface.100}',
              color: '{surface.950}',
            },
            plain: {
              hoverBackground: '{surface.50}',
              activeBackground: '{surface.100}',
              color: '{surface.700}',
            },
          },
          link: {
            color: '{primary.color}',
            hoverColor: '{primary.color}',
            activeColor: '{primary.color}',
          },
        },
        dark: {
          root: {
            primary: {
              background: '{primary.color}',
              text: '{primary.inverseColor}',
              hoverBackground: '{primary.hoverColor}',
              activeBackground: '{primary.activeColor}',
              disabledBackground: '{primary.disabledColor}',
              disabledText: '{text.disabled}',
            },
            secondary: {
              background: '{secondary.color}',
              text: '{secondary.inverseColor}',
              hoverBackground: '{secondary.hoverColor}',
              activeBackground: '{secondary.activeColor}',
              disabledBackground: '{secondary.disabledColor}',
              disabledText: '{text.disabled}',
            },
            success: {
              background: '{success.color}',
              text: '{success.inverseColor}',
              hoverBackground: '{success.hoverColor}',
              activeBackground: '{success.activeColor}',
              disabledBackground: '{success.disabledColor}',
              disabledText: '{text.disabled}',
            },
            danger: {
              background: '{danger.color}',
              text: '{danger.inverseColor}',
              hoverBackground: '{danger.hoverColor}',
              activeBackground: '{danger.activeColor}',
              disabledBackground: '{danger.disabledColor}',
              disabledText: '{text.disabled}',
            },
            warn: {
              background: '{warn.color}',
              text: '{warn.inverseColor}',
              hoverBackground: '{warn.hoverColor}',
              activeBackground: '{warn.activeColor}',
              disabledBackground: '{warn.disabledColor}',
              disabledText: '{text.disabled}',
            },
            info: {
              background: '{info.color}',
              text: '{info.inverseColor}',
              hoverBackground: '{info.hoverColor}',
              activeBackground: '{info.activeColor}',
              disabledBackground: '{info.disabledColor}',
              disabledText: '{text.disabled}',
            },
            accent: {
              background: '{accent.color}',
              text: '{accent.inverseColor}',
              hoverBackground: '{accent.hoverColor}',
              activeBackground: '{accent.activeColor}',
              disabledBackground: '{accent.disabledColor}',
              disabledText: '{text.disabled}',
            },
          },
          outlined: {
            primary: {
              hoverBackground: 'color-mix(in srgb, {primary.color}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {primary.color}, transparent 84%)',
              borderColor: '{primary.700}',
              color: '{primary.color}',
            },
            secondary: {
              hoverBackground: 'rgba(255,255,255,0.04)',
              activeBackground: 'rgba(255,255,255,0.16)',
              borderColor: '{secondary.700}',
              color: '{secondary.400}',
            },
            success: {
              hoverBackground: 'color-mix(in srgb, {success.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {success.400}, transparent 84%)',
              borderColor: '{success.700}',
              color: '{success.400}',
            },
            info: {
              hoverBackground: 'color-mix(in srgb, {info.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {info.400}, transparent 84%)',
              borderColor: '{info.700}',
              color: '{info.400}',
            },
            warn: {
              hoverBackground: 'color-mix(in srgb, {warn.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {warn.400}, transparent 84%)',
              borderColor: '{warn.700}',
              color: '{warn.400}',
            },
            neutral: {
              hoverBackground: 'color-mix(in srgb, {neutral.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {neutral.400}, transparent 84%)',
              borderColor: '{neutral.700}',
              color: '{neutral.400}',
            },
            danger: {
              hoverBackground: 'color-mix(in srgb, {danger.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {danger.400}, transparent 84%)',
              borderColor: '{danger.700}',
              color: '{danger.400}',
            },
            contrast: {
              hoverBackground: '{surface.800}',
              activeBackground: '{surface.700}',
              borderColor: '{surface.500}',
              color: '{surface.0}',
            },
            white: {
              hoverBackground: '{surface.800}',
              activeBackground: '{surface.700}',
              borderColor: '{surface.600}',
              color: '{surface.0}',
            },
          },
          text: {
            primary: {
              hoverBackground: 'color-mix(in srgb, {primary.color}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {primary.color}, transparent 84%)',
              color: '{primary.color}',
            },
            secondary: {
              hoverBackground: '{secondary.700}',
              activeBackground: '{secondary.600}',
              color: '{secondary.300}',
            },
            success: {
              hoverBackground: 'color-mix(in srgb, {success.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {success.400}, transparent 84%)',
              color: '{success.400}',
            },
            info: {
              hoverBackground: 'color-mix(in srgb, {info.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {info.400}, transparent 84%)',
              color: '{info.400}',
            },
            warn: {
              hoverBackground: 'color-mix(in srgb, {warn.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {warn.400}, transparent 84%)',
              color: '{warn.400}',
            },
            help: {
              hoverBackground: 'color-mix(in srgb, {purple.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {purple.400}, transparent 84%)',
              color: '{purple.400}',
            },
            danger: {
              hoverBackground: 'color-mix(in srgb, {danger.400}, transparent 96%)',
              activeBackground: 'color-mix(in srgb, {danger.400}, transparent 84%)',
              color: '{danger.400}',
            },
            contrast: {
              hoverBackground: '{surface.800}',
              activeBackground: '{surface.700}',
              color: '{surface.0}',
            },
            plain: {
              hoverBackground: '{surface.800}',
              activeBackground: '{surface.700}',
              color: '{surface.0}',
            },
          },
          link: {
            color: '{primary.color}',
            hoverColor: '{primary.color}',
            activeColor: '{primary.color}',
          },
        },
      },
    },
  },
});
