name: tumapply
volumes:
  clearflask-data:
    driver: local
  clearflask-connect-data:
    driver: local
  clearflask-db:
    driver: local
  localstack-data:
    driver: local
services:
  clearflask-db:
    image: mysql:5.7
    platform: linux/amd64
    command:
      - 'mysqld'
      - '--port=3306'
      - '--sql-mode=IGNORE_SPACE'
      - '--explicit-defaults-for-timestamp'
      - '--secure-file-priv=/tmp'
    volumes:
      - clearflask-db:/var/lib/mysql
    ports:
      - 3307:3306
    env_file:
      - ../../../.env.local
    environment:
      - MYSQL_DATABASE=clearflask
  clearflask-server:
    image: ghcr.io/clearflask/clearflask-server:2.2.0
    entrypoint: ['sh', '/opt/clearflask/entrypoint.sh']
    ports:
      - 18080:8080
      # JMX (optional, for debugging / monitoring)
      # - 9950:9950
      # - 9951:9951
    env_file:
      - ../../../.env.local
    environment:
      - CLEARFLASK_ENVIRONMENT=PRODUCTION_SELF_HOST
      - CLEARFLASK_CREATE_SERVER_CONFIG_IF_MISSING=1
      - CLEARFLASK_DB_TYPE=mysql
      - CLEARFLASK_DB_HOST=clearflask-db
      - CLEARFLASK_DB_PORT=3306
      - CLEARFLASK_DB_DATABASE=clearflask
    volumes:
      - clearflask-data:/opt/clearflask/data
      - ./clearflask/config-selfhost.cfg.template:/opt/clearflask/config-selfhost.cfg.template:ro
      - ./clearflask/entrypoint.sh:/opt/clearflask/entrypoint.sh:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/api/health']
      interval: 5s
      timeout: 15s
      retries: 2
    depends_on:
      - clearflask-db
      - localstack
  clearflask-connect:
    image: ghcr.io/clearflask/clearflask-connect:2.2.0
    depends_on:
      - clearflask-server
    ports:
      - 18081:9080
      - 18443:9443
    environment:
      - NODE_ENV=production
      - ENV=selfhost
      - CLEARFLASK_CREATE_CONNECT_CONFIG_IF_MISSING=1
    volumes:
      - clearflask-connect-data:/opt/clearflask/
  localstack:
    image: localstack/localstack:4.7.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,dynamodb
    volumes:
      - localstack-data:/var/lib/localstack
