version: "3"
services:
  app:
    image: ghcr.io/your-org-or-user/tum-apply:${IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
