# docker-compose.test.yml
version: '3.8'
services:
  tum-apply:
    image: ls1intum/tum-apply:${IMAGE_TAG}
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod # or whatever profile you want
    restart: unless-stopped
