name: '🐛 Bug (Developer)'
description: Quick issue for TumApply
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Bug Summary
      description: What's broken? What did you expect? Which page is affected?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notes
      description: Anything else? (optional)
