name: tumapply
services:
  mysql:
    image: mysql:9.4.0
    env_file:
      - .env
    expose:
      - '3306'
    command: mysqld --lower_case_table_names=1 --tls-version='' --character_set_server=utf8mb4  --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --silent
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 300s
    restart: always
    networks:
      - shared-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '5432:5432'
  tumapply:
    image: 'ghcr.io/ls1intum/tum-apply:${IMAGE_TAG}'
    env_file:
      - .env
    expose:
      - '8080'
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:8080/actuator/health || exit 1
      start_period: 100s
      interval: 1s
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - shared-network
  nginx:
    image: nginx:1.28.0-alpine-slim
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
    healthcheck:
      test: service nginx status || exit 1
      start_period: 10s
    restart: always
    depends_on:
      tumapply:
        condition: service_healthy
    volumes:
      - ./src/main/resources/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - type: bind
        source: '/var/lib/rbg-cert/live/fullchain.pem'
        target: '/certs/fullchain.pem'
      - type: bind
        source: '/var/lib/rbg-cert/live/privkey.pem'
        target: '/certs/privkey.pem'
    networks:
      - shared-network

networks:
  shared-network:
    name: tumapply-shared-network
    driver: bridge

volumes:
  mysql_data:
