name: Validate PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: Slashgear/action-check-pr-title@v5.0.1
        with:
          regexp: '^`(Usability|Performance|Development|General)`:\s[A-Z].*$'
